name: PR CI

on:
  pull_request:
    branches:
      - "main"
      - "develop/*"
    types: [ opened, synchronize, reopened, ready_for_review ]

permissions:
  contents: read

concurrency:
  group: pr-ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Build, Test, Coverage Gate (JDK 21)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Build + Test + Coverage Verify
        run: |
          ./gradlew --no-daemon --stacktrace --info \
            clean build check

      - name: Publish Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          retention-days: 7
          if-no-files-found: ignore
          path: |
            build/test-results/**
            build/reports/tests/**
            **/build/test-results/**
            **/build/reports/tests/**

      - name: Publish Coverage Reports (Kover)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          retention-days: 7
          if-no-files-found: ignore
          path: |
            build/reports/kover/**
            build/custom.xml
            **/build/reports/kover/**
            **/build/custom.xml

  lint:
    name: Lint and Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Run linters (adjust if tools are present)
        run: |
          # ツール導入状況に応じて有効化
          ./gradlew --no-daemon --stacktrace \
            ktlintCheck detekt || true

      - name: Upload Lint Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-reports
          retention-days: 7
          if-no-files-found: ignore
          path: |
            build/reports/ktlint/**
            **/build/reports/ktlint/**
            build/reports/detekt/**
            **/build/reports/detekt/**

  verify-artifacts:
    name: Verify Artifacts Shape
    runs-on: ubuntu-latest
    needs: [ build-test ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Assemble Jars
        run: |
          ./gradlew --no-daemon --stacktrace assemble

      - name: Verify jars (manifest/classes present)
        run: |
          set -e
          echo "Listing built jars:"
          find . -path "**/build/libs/*.jar" -type f -print
          echo "Check at least one runtime jar exists"
          test -n "$(find . -path "**/build/libs/*.jar" -type f | head -n1)"
          echo "Show manifest of first jar:"
          JAR_FILE=$(find . -path "**/build/libs/*.jar" -type f | head -n1)
          jar tf "$JAR_FILE" | head -n 50
          jar xf "$JAR_FILE" META-INF/MANIFEST.MF || true
          test -f META-INF/MANIFEST.MF || true
          rm -rf META-INF || true

      - name: Upload Built Jars
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: verified-jars
          retention-days: 7
          if-no-files-found: ignore
          path: |
            **/build/libs/*.jar