name: Publish to Maven Central

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    name: Publish (Snapshot on main, Release on tag)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Cache Gradle Build Cache
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches/build-cache-1
          key: gradle-build-cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-build-cache-${{ runner.os }}-

      - name: Set CI_TAG for release tags (strip leading 'v')
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "CI_TAG=${GITHUB_REF_NAME#v}" >> "$GITHUB_ENV"

      - name: Decode signing key
        run: |
          echo "${{ secrets.SIGNING_IN_MEMORY_KEY }}" | base64 -d > signing.key
          echo "ORG_GRADLE_PROJECT_signingInMemoryKey=$(cat signing.key)" >> $GITHUB_ENV

      - name: Publish to Maven Central
        env:
          # Map GitHub Secrets to Gradle project properties expected by Vanniktech plugin
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_IN_MEMORY_KEY_PASSWORD }}
        run: |
          ./gradlew --no-daemon --stacktrace --info \
            publishToMavenCentral
